name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

 #   - name: Create tests directory and test.py
 #     run: |
 #       mkdir tests
 #       echo "def test_dummy():\n    assert True" > tests/test.py

    - name: List files in tests directory
      run: |
        ls -R tests

    - name: Run tests
      run: |
        python -m unittest discover -p '*_test.py' tests


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Login to docker
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Deploy to Docker Hub
      run: |
        docker build -t flask-hello-app .
        docker tag flask-hello-app "${{ secrets.DOCKER_USERNAME }}/flask-hello-app:latest" | tr '[:upper:]' '[:lower:]'
        docker push "${{ secrets.DOCKER_USERNAME }}/flask-hello-app:latest"
  
